name: rocky_rewards
description: A new Flutter project.

publish_to: 'none'
version: 1.3.5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.8
  rxdart: ^0.26.0
  get: ^4.3.8
  shimmer: ^2.0.0
  toggle_switch: ^1.3.0
  numberpicker: ^2.1.1
  date_utils: ^0.2.0
  path_provider: ^2.0.6
  open_file: ^3.2.1
  syncfusion_flutter_pdf: ^19.3.48-beta
  month_picker_dialog: ^0.4.0
  fluttercontactpicker: ^4.5.1
  share: ^2.0.4

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.1
  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: 'assets/background.png'
  adaptive_icon_foreground: 'assets/foreground.png'

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#303030"
  image: assets/icon_red.png

flutter:
  uses-material-design: true
  assets:
    - assets/icon_white.png
    - assets/icon_red.png
    - assets/template_pdf.pdf